name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        with:
          server_ip: ${{ secrets.SERVER_IP }}
          server_port: ${{ secrets.SERVER_PORT }}
          remote_username: ${{ secrets.SERVER_USERNAME }}
          remote_private_key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: ./build/
          target: /var/www/chartmaker
          args: -avz --delete

